version: "3"

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
    command: minio server --console-address ":9001" /data
    networks:
      - vot-net
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: changeme
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: "mc ready local"
      interval: 5s
      timeout: 5s
      retries: 5

  createbucket:
    image: quay.io/minio/mc:RELEASE.2025-02-15T10-36-16Z
    networks:
      - vot-net
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 root changeme;
      /usr/bin/mc mb myminio/vot-backend;
      /usr/bin/mc anonymous set none myminio/vot-backend;
      exit 0;
      "

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - vot-net
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:16-alpine
    networks:
      - vot-net
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vot-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

  vot-backend:
    build: .
    container_name: vot-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - vot-net
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      SERVICE_TOKEN: 90jrtire8i9u4353asdasdasd
      MEDIA_CONVERTER_HOSTNAME: http://localhost:3000
      MEDIA_CONVERTER_TOKEN: x
      TRANSLATE_TEXT_HOSTNAME: https://translate.toil.cc
      S3_REGION: eu-central-1
      S3_ENDPOINT: http://minio:9000
      S3_PRESIGNED_ENDPOINT: http://127.0.0.1:9000
      S3_BUCKET: vot-backend
      S3_ACCESS_KEY_ID: root
      S3_SECRET_ACCESS_KEY: changeme
      S3_FORCE_PATH_STYLE: true
      REDIS_HOST: redis
      POSTGRES_NAME: vot-backend
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

networks:
  vot-net:
    driver: bridge
